# Generated by Django 4.1.7 on 2023-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('maintenance_type', models.CharField(max_length=1)),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
