# Generated by Django 4.1.7 on 2023-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='keep_subsidiary',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
