# Generated by Django 4.1.7 on 2023-04-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0006_account_keep_subsidiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountMaintenance.currency'),
        ),
    ]
