# Generated by Django 4.1.7 on 2023-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0007_alter_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
