# Generated by Django 4.1.7 on 2023-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0008_alter_currency_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
