# Generated by Django 4.1.7 on 2023-04-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0009_alter_account_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='maintenance_type',
        ),
    ]
