# Generated by Django 4.1.7 on 2023-04-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0011_accountchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
