# Generated by Django 4.1.7 on 2023-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0016_delete_accountactive_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_serial', models.IntegerField()),
                ('account_type', models.CharField(max_length=3)),
                ('balance_option', models.IntegerField()),
                ('mapping_asset', models.IntegerField()),
                ('mapping_liab', models.IntegerField()),
            ],
        ),
    ]
