# Generated by Django 4.1.7 on 2023-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountMaintenance', '0017_accountoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountoptions',
            name='mapping_asset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountoptions',
            name='mapping_liab',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
